name: Build and Release Python MySQL CLI App

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0

jobs:
  build:
    runs-on: windows-latest  # Switch to Windows to produce .exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mysql-connector-python pyinstaller

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile main.py  --icon=app_icon.ico

      - name: Upload .exe as artifact
        uses: actions/upload-artifact@v4
        with:
          name: MySecureDBManager
          path: dist/main.exe  # This is the compiled .exe

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download .exe artifact
        uses: actions/download-artifact@v4
        with:
          name: MySecureDBManager
          path: .

      - name: Upload .exe to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: MySecureDBManager.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
