\name: Build and Release MySecureDBManager

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mysql-connector-python pyinstaller

      - name: Build .exe with PyInstaller
        run: |
          pyinstaller --onefile main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MySecureDBManager
          path: dist/main.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: MySecureDBManager

      - name: Upload .exe to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: main.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
